# app.py
from flask import Flask, request, jsonify, send_from_directory, render_template
from werkzeug.security import check_password_hash
import os

import products
import orders
import payments
import img

from database import admins_db, app_config_db, brands_db
from model import admin_from_db, config_from_db, brand_from_db


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
IMAGES_DIR = os.path.join(BASE_DIR, "images")

app = Flask(__name__, static_folder="static", template_folder="templates")


# =========================================================
# Helpers
# =========================================================

def _safe_json(handler):
    try:
        return handler()
    except Exception as error:
        return jsonify({
            "ok": False,
            "message": str(error),
        }), 500


def _password_matches(raw_password: str, stored_password: str) -> bool:
    """
    Supports two cases:
    1. Plain text while developing, example: --admin
    2. Werkzeug hash later, example generated by generate_password_hash()
    """

    raw_password = str(raw_password or "")
    stored_password = str(stored_password or "")

    if not raw_password or not stored_password:
        return False

    if stored_password == raw_password:
        return True

    try:
        return check_password_hash(stored_password, raw_password)
    except Exception:
        return False


# =========================================================
# Pages
# =========================================================

@app.route("/")
@app.route("/main")
def home():
    return render_template("main.html")


@app.route("/admin")
def admin():
    return render_template("admin.html")


# =========================================================
# Config
# =========================================================

@app.route("/api/config", methods=["GET"])
def get_config():
    def handler():
        rows = app_config_db.get_all(order_by="id", desc=False, limit=1)

        if not rows:
            return jsonify({
                "app": {
                    "title": "AM Cosmetic Hub",
                    "currency": "PHP",
                    "theme": "light",
                    "acceptMode": "MANUAL",
                },
                "fees": {
                    "codPercent": 3,
                    "ewalletPercent": 2,
                    "counterPercent": 2,
                    "cardPercent": 0,
                },
                "images": {
                    "qrcode": "",
                    "productFallback": "",
                    "brandFallback": "",
                },
                "tracking": {
                    "prefix": "AMCH",
                },
            })

        return jsonify(config_from_db(rows[0]))

    return _safe_json(handler)


# =========================================================
# Brands
# =========================================================

@app.route("/api/brands", methods=["GET"])
def get_brands():
    def handler():
        rows = brands_db.get_all(order_by="name", desc=False)
        brands = [brand_from_db(row) for row in rows]
        return jsonify({"brands": brands})

    return _safe_json(handler)


# =========================================================
# Admins
# =========================================================

@app.route("/api/admins", methods=["GET"])
def get_admins():
    def handler():
        rows = admins_db.get_all(order_by="created_at", desc=False)
        admins = [admin_from_db(row) for row in rows]
        return jsonify({"admins": admins})

    return _safe_json(handler)


@app.route("/api/admin/login", methods=["POST"])
def admin_login():
    def handler():
        payload = request.get_json(silent=True) or {}

        username = str(payload.get("username", "")).strip()
        password = str(payload.get("password", "")).strip()

        if not username or not password:
            return jsonify({
                "ok": False,
                "message": "Username and password are required.",
            }), 400

        admin_row = admins_db.find_one("username", username)

        if not admin_row:
            return jsonify({
                "ok": False,
                "message": "Invalid username or password.",
            }), 401

        stored_password = (
            admin_row.get("password_hash")
            or admin_row.get("password")
            or ""
        )

        if not _password_matches(password, stored_password):
            return jsonify({
                "ok": False,
                "message": "Invalid username or password.",
            }), 401

        return jsonify({
            "ok": True,
            "admin": admin_from_db(admin_row),
        })

    return _safe_json(handler)


# =========================================================
# IP
# =========================================================

@app.route("/api/ip", methods=["GET"])
def get_ip():
    forwarded = request.headers.get("X-Forwarded-For", "").split(",")[0].strip()
    ip_addr = forwarded or request.remote_addr or "Unavailable"
    return jsonify({"ip": ip_addr})


# =========================================================
# Products
# =========================================================

@app.route("/api/products", methods=["GET", "POST", "DELETE"])
def products_route():
    def handler():
        if request.method == "GET":
            return jsonify({"products": products.get_all()})

        if request.method == "POST":
            payload = request.get_json(silent=True) or {}
            result = products.create_product_entry(payload)
            return jsonify(result), (200 if result.get("ok") else 400)

        result = products.clear_products()
        return jsonify(result), (200 if result.get("ok") else 400)

    return _safe_json(handler)


@app.route("/api/products/<string:product_id>", methods=["PATCH", "DELETE"])
def product_entry_route(product_id):
    def handler():
        if request.method == "PATCH":
            payload = request.get_json(silent=True) or {}

            full_replace_keys = [
                "pricing",
                "name",
                "description",
                "images",
                "brandID",
                "brandId",
                "brand_id",
                "createdAt",
                "updatedAt",
                "reviews",
                "cartAddedCount",
            ]

            if any(key in payload for key in full_replace_keys):
                result = products.replace_product_entry(product_id, payload)
            else:
                result = products.update_product(product_id, payload)

            return jsonify(result), (200 if result.get("ok") else 404)

        result = products.delete_product_entry(product_id)
        return jsonify(result), (200 if result.get("ok") else 404)

    return _safe_json(handler)


@app.route("/api/products/<string:product_id>/cart", methods=["PATCH"])
def patch_product_cart(product_id):
    def handler():
        payload = request.get_json(silent=True) or {}
        delta = payload.get("delta", 0)

        result = products.update_cart_count(product_id, delta)
        return jsonify(result), (200 if result.get("ok") else 404)

    return _safe_json(handler)


# =========================================================
# Orders
# =========================================================

@app.route("/api/orders", methods=["GET", "POST"])
def orders_route():
    def handler():
        if request.method == "GET":
            return jsonify({"orders": orders.get_all()})

        payload = request.get_json(silent=True) or {}
        result = orders.create(payload)
        return jsonify(result), (200 if result.get("ok") else 400)

    return _safe_json(handler)


@app.route("/api/orders/<string:ref>", methods=["GET"])
def track_order(ref):
    def handler():
        result = orders.track(ref)
        return jsonify(result), (200 if result.get("found") else 404)

    return _safe_json(handler)


# =========================================================
# Payments
# =========================================================

@app.route("/api/payments", methods=["GET", "POST"])
def payments_route():
    def handler():
        if request.method == "GET":
            return jsonify({"payments": payments.get_all()})

        payload = request.get_json(silent=True) or {}
        payment_payload = payload.get("payment", payload)

        result = payments.create(payment_payload)
        return jsonify(result), (200 if result.get("ok") else 400)

    return _safe_json(handler)


@app.route("/api/payments/<string:payment_id>", methods=["PATCH"])
def patch_payment(payment_id):
    def handler():
        payload = request.get_json(silent=True) or {}
        status = payload.get("status", "Pending")

        result = payments.update_status(payment_id, status)
        return jsonify(result), (200 if result.get("ok") else 404)

    return _safe_json(handler)


# =========================================================
# Reviews
# =========================================================

@app.route("/api/reviews", methods=["GET"])
def get_reviews():
    def handler():
        return jsonify({"reviews": products.get_all_reviews()})

    return _safe_json(handler)


@app.route("/api/reviews/<string:review_id>/reply", methods=["POST"])
def reply_review(review_id):
    def handler():
        payload = request.get_json(silent=True) or {}

        reply = str(payload.get("reply", "")).strip()
        admin_name = str(payload.get("admin", "Administrator")).strip() or "Administrator"

        result = products.reply_to_review(review_id, reply, admin_name)
        return jsonify(result), (200 if result.get("ok") else 404)

    return _safe_json(handler)


# =========================================================
# Images
# =========================================================

@app.route("/api/images/upload", methods=["POST"])
def upload_image():
    """
    Render/Supabase version:
    This endpoint now accepts image URLs.

    JSON example:
    {
        "folder": "product",
        "url": "https://res.cloudinary.com/.../image.png"
    }

    Form-data example:
    folder=product
    url=https://res.cloudinary.com/.../image.png

    If frontend still sends a file, img.py will reject local upload
    and explain that hosted image URL is required.
    """

    payload = request.get_json(silent=True) or {}

    folder = (
        payload.get("folder")
        or request.form.get("folder")
        or "product"
    )

    image_url = (
        payload.get("url")
        or payload.get("imageUrl")
        or request.form.get("url")
        or request.form.get("imageUrl")
        or ""
    )

    file = request.files.get("file")

    result = img.save(
        file=file,
        folder=folder,
        url=image_url,
    )

    return jsonify(result), (200 if result.get("ok") else 400)


@app.route("/images/<path:filename>", methods=["GET"])
def serve_image(filename):
    return send_from_directory(IMAGES_DIR, filename)


@app.route("/images/product/<path:filename>", methods=["GET"])
def serve_product_image(filename):
    return send_from_directory(os.path.join(IMAGES_DIR, "product"), filename)


@app.route("/images/brand/<path:filename>", methods=["GET"])
def serve_brand_image(filename):
    return send_from_directory(os.path.join(IMAGES_DIR, "brand"), filename)


# =========================================================
# Health Check
# =========================================================

@app.route("/api/health", methods=["GET"])
def health_check():
    return jsonify({
        "ok": True,
        "message": "Backend is running.",
    })


# =========================================================
# Run Local
# =========================================================

if __name__ == "__main__":
    app.run(debug=True)